package service

// NaYinKnowledge holds the complete 30-type na-yin knowledge base.
// Indexed by na-yin name (e.g. "杨柳木") → NaYinEntry.
var NaYinKnowledge = map[string]NaYinEntry{
	// ── 金 ──────────────────────────────────────────────────────────────────
	"海中金": {
		Name:         "海中金",
		StemBranches: []string{"甲子", "乙丑"},
		Element:      "金",
		ImageDesc:    "沉卧海底，光芒内敛，需磨砺方显价值",
		Personality:  "外表沉稳，内心丰藏，厚积薄发型",
		EnergyStage:  "墓",
		ModernExt:    "像深藏的宝藏或海底珍珠，需要挖掘和磨练才能展现真正价值",
		Judgments:    []string{"与父母中一人缘薄", "早年运气平常，中年后渐入佳境"},
	},
	"金泊金": {
		Name:         "金泊金",
		StemBranches: []string{"壬寅", "癸卯"},
		Element:      "金",
		ImageDesc:    "薄金贴附，浮于表面，依赖依附之美",
		Personality:  "善于交际，变通灵活，依赖性较强",
		EnergyStage:  "病",
		ModernExt:    "像镀金工艺品，光泽外露但根基较浅，需要借助他人平台",
		Judgments:    []string{"善交际变通", "早年运势辛苦", "根基不稳"},
	},
	"白蜡金": {
		Name:         "白蜡金",
		StemBranches: []string{"庚辰", "辛巳"},
		Element:      "金",
		ImageDesc:    "蜡封之金，光泽冷藏，蓄势待发",
		Personality:  "外表柔和，内心刚强，有耐性善于等待时机",
		EnergyStage:  "养",
		ModernExt:    "像封存的贵重矿石，积累阶段需要时间",
		Judgments:    []string{"早年运气平常", "中年以后渐有起色", "有耐性"},
	},
	"沙中金": {
		Name:         "沙中金",
		StemBranches: []string{"甲午", "乙未"},
		Element:      "金",
		ImageDesc:    "散于沙砾，淘尽黄沙始见金",
		Personality:  "历经磨练方成器，大器晚成型",
		EnergyStage:  "死",
		ModernExt:    "像河床底下的金沙，需要经历淘洗才能提炼",
		Judgments:    []string{"大器晚成", "需经历磨练方显才华", "中年转运"},
	},
	"剑锋金": {
		Name:         "剑锋金",
		StemBranches: []string{"壬申", "癸酉"},
		Element:      "金",
		ImageDesc:    "剑刃锋金，锐利无比，可斩断一切",
		Personality:  "刚强果敢，行动力强，言出必行",
		EnergyStage:  "绝",
		ModernExt:    "像一把出鞘的利剑，锐利果决，适合开拓性工作",
		Judgments:    []string{"性格刚强", "言出必行", "过于锋利易折"},
	},
	"钗钏金": {
		Name:         "钗钏金",
		StemBranches: []string{"庚戌", "辛亥"},
		Element:      "金",
		ImageDesc:    "女性装饰之金，贵重精致，需小心保管",
		Personality:  "外表光鲜，注重形象，有艺术气质",
		EnergyStage:  "衰",
		ModernExt:    "像精致的首饰，需要保护和保养",
		Judgments:    []string{"有艺术气质", "外表光鲜", "内心细膕"},
	},

	// ── 木 ──────────────────────────────────────────────────────────────────
	"杨柳木": {
		Name:         "杨柳木",
		StemBranches: []string{"壬午", "癸未"},
		Element:      "木",
		ImageDesc:    "对应午未之月，木由盛转衰，杨柳枝干柔弱，随风摇曳",
		Personality:  "善交际变通，易受外界牵引，柔弱而富有弹性",
		EnergyStage:  "死墓",
		ModernExt:    "像随风飘荡的柳枝，适应性强但根基不稳",
		Judgments:    []string{"善交际变通", "易受外界牵引", "根基不稳", "早年运势辛苦"},
	},
	"松柏木": {
		Name:         "松柏木",
		StemBranches: []string{"庚寅", "辛卯"},
		Element:      "木",
		ImageDesc:    "对应寅卯之月春季，木气旺盛，庚辛金象征松柏在霜雪中仍常青",
		Personality:  "意志坚定，坚韧不拔，在逆境中更显品格",
		EnergyStage:  "旺",
		ModernExt:    "像岁寒三友中的松柏，经得起考验，愈冷愈青",
		Judgments:    []string{"意志坚定", "晚运昌隆", "在逆境中更显品格"},
	},
	"大林木": {
		Name:         "大林木",
		StemBranches: []string{"戊辰", "己巳"},
		Element:      "木",
		ImageDesc:    "对应辰巳之月，春末夏初，万物生长茂盛，树木成林",
		Personality:  "包容力强，资源丰富，气势极盛",
		EnergyStage:  "旺",
		ModernExt:    "像原始大森林，包容万物，资源丰富",
		Judgments:    []string{"包容力强", "资源丰富", "能承受强金克制而不伤"},
	},
	"平地木": {
		Name:         "平地木",
		StemBranches: []string{"戊戌", "己亥"},
		Element:      "木",
		ImageDesc:    "对应戌亥之月，秋冬之交，万物闭藏，木气归于土中，如被人工培育的园林之木",
		Personality:  "依赖环境扶持，需贵人栽培，厚积薄发型",
		EnergyStage:  "墓",
		ModernExt:    "像园林中的观赏木，需要人工培育和环境支持",
		Judgments:    []string{"依赖环境扶持", "需贵人提携", "厚积薄发"},
	},
	"桑柘木": {
		Name:         "桑柘木",
		StemBranches: []string{"壬子", "癸丑"},
		Element:      "木",
		ImageDesc:    "对应子丑之月，冬季，天寒地冻，木气屈曲难申",
		Personality:  "默默付出，间接成就他人，有奉献精神",
		EnergyStage:  "死",
		ModernExt:    "像桑树喂养蚕丝，默默奉献，滋养他人",
		Judgments:    []string{"默默付出", "间接成就他人", "有奉献精神"},
	},
	"石榴木": {
		Name:         "石榴木",
		StemBranches: []string{"庚申", "辛酉"},
		Element:      "木",
		ImageDesc:    "申为七月，酉为八月，木已凋零，但石榴正果实累累",
		Personality:  "外刚内柔，多子多福，生命力极其顽强",
		EnergyStage:  "绝",
		ModernExt:    "像秋天果实累累的石榴，外表坚硬但内心丰盛",
		Judgments:    []string{"多子多福", "内在热情奔放", "生命力极其顽强"},
	},

	// ── 水 ──────────────────────────────────────────────────────────────────
	"涧下水": {
		Name:         "涧下水",
		StemBranches: []string{"丙子", "丁丑"},
		Element:      "水",
		ImageDesc:    "山间细流，清冽纯净，源短流浅",
		Personality:  "清高自守，感情细腻，有艺术气质",
		EnergyStage:  "旺",
		ModernExt:    "像山间的清澈溪流，水质纯净但规模有限",
		Judgments:    []string{"清高自守", "感情细腻", "有艺术气质"},
	},
	"长流水": {
		Name:         "长流水",
		StemBranches: []string{"壬辰", "癸巳"},
		Element:      "水",
		ImageDesc:    "源远流长，连绵不绝，生生不息",
		Personality:  "适应力强，善于变化，韧性强",
		EnergyStage:  "旺",
		ModernExt:    "像长江黄河，源远流长，适应性强",
		Judgments:    []string{"适应力强", "善于变化", "韧性十足"},
	},
	"大溪水": {
		Name:         "大溪水",
		StemBranches: []string{"甲寅", "乙卯"},
		Element:      "水",
		ImageDesc:    "山间大溪，水势汹涌，气势磅礴",
		Personality:  "气势旺盛，行动力强，有领导力",
		EnergyStage:  "死",
		ModernExt:    "像山间奔腾的溪流，动力充沛但需要引导",
		Judgments:    []string{"气势旺盛", "行动力强", "有领导力"},
	},
	"天河水": {
		Name:         "天河水",
		StemBranches: []string{"丙午", "丁未"},
		Element:      "水",
		ImageDesc:    "银河之水，从天而降，光明璀璨",
		Personality:  "光明磊落，志向高远，有大局观",
		EnergyStage:  "帝旺",
		ModernExt:    "像天上的银河，高远明亮，有宏观视野",
		Judgments:    []string{"光明磊落", "志向高远", "有大局观"},
	},
	"井泉水": {
		Name:         "井泉水",
		StemBranches: []string{"壬申", "癸酉"},
		Element:      "水",
		ImageDesc:    "地下涌泉，清凉甘冽，源源不断",
		Personality:  "内心深邃，思考深入，有持续力",
		EnergyStage:  "绝",
		ModernExt:    "像地下涌出的泉水，内在深邃而持久",
		Judgments:    []string{"内心深邃", "思考深入", "有持续力"},
	},
	"大海水": {
		Name:         "大海水",
		StemBranches: []string{"壬戌", "癸亥"},
		Element:      "水",
		ImageDesc:    "汪洋大海，包容万物，气象宏大",
		Personality:  "胸怀宽广，包容力强，有大格局",
		EnergyStage:  "墓",
		ModernExt:    "像浩瀚的海洋，包容一切，格局宏大",
		Judgments:    []string{"胸怀宽广", "包容力强", "大格局"},
	},

	// ── 火 ──────────────────────────────────────────────────────────────────
	"霹雳火": {
		Name:         "霹雳火",
		StemBranches: []string{"戊子", "己丑"},
		Element:      "火",
		ImageDesc:    "雷电之火，爆发力强，来去迅猛",
		Personality:  "爆发力强，变化迅猛，行动迅速",
		EnergyStage:  "旺",
		ModernExt:    "像雷暴中的闪电，来势凶猛但短暂",
		Judgments:    []string{"爆发力强", "变化迅猛", "行动迅速", "来得快去也快"},
	},
	"炉中火": {
		Name:         "炉中火",
		StemBranches: []string{"丙寅", "丁卯"},
		Element:      "火",
		ImageDesc:    "炉火锻造，聚焦持久，能量可控",
		Personality:  "专注持久，意志坚定，有耐性",
		EnergyStage:  "旺",
		ModernExt:    "像熔炉中的火焰，聚焦而持久",
		Judgments:    []string{"专注持久", "意志坚定", "有耐性"},
	},
	"覆灯火": {
		Name:         "覆灯火",
		StemBranches: []string{"甲辰", "乙巳"},
		Element:      "火",
		ImageDesc:    "灯火覆护，光明稳定，范围有限",
		Personality:  "照亮一方，守护家园，适合小范围",
		EnergyStage:  "衰",
		ModernExt:    "像油灯的光，照亮身边但范围有限",
		Judgments:    []string{"照亮一方", "守护家园", "适合小范围发展"},
	},
	"天上火": {
		Name:         "天上火",
		StemBranches: []string{"戊午", "己未"},
		Element:      "火",
		ImageDesc:    "太阳当空，普照大地，能量最高",
		Personality:  "刚柔并济，高能量，高关注度",
		EnergyStage:  "帝旺",
		ModernExt:    "像正午的太阳，光芒万丈，照耀四方",
		Judgments:    []string{"刚柔并济", "高能量", "Top级别", "普照大地"},
	},
	"山下火": {
		Name:         "山下火",
		StemBranches: []string{"丙申", "丁酉"},
		Element:      "火",
		ImageDesc:    "夕阳余晖，能量减弱，但有余韵",
		Personality:  "温和内敛，有后劲，晚运较好",
		EnergyStage:  "病",
		ModernExt:    "像傍晚的火烧云，余晖美丽但即将消退",
		Judgments:    []string{"温和内敛", "有后劲", "晚运较好"},
	},
	"山头火": {
		Name:         "山头火",
		StemBranches: []string{"甲戌", "乙亥"},
		Element:      "火",
		ImageDesc:    "火山之火，能量内藏，休眠状态",
		Personality:  "外表平静，内心炽热，潜力内藏",
		EnergyStage:  "墓",
		ModernExt:    "像休眠的火山，表面平静但内蕴巨大能量",
		Judgments:    []string{"外表平静", "内心炽热", "潜力内藏"},
	},

	// ── 土 ──────────────────────────────────────────────────────────────────
	"壁上土": {
		Name:         "壁上土",
		StemBranches: []string{"丙寅", "丁卯"},
		Element:      "土",
		ImageDesc:    "墙壁上的土，依附建筑，有保护作用",
		Personality:  "有依靠，有庇护，善于借势",
		EnergyStage:  "病",
		ModernExt:    "像建筑物的墙壁，需要依附于结构",
		Judgments:    []string{"有依靠", "善于借势", "需有平台才能发挥"},
	},
	"城头土": {
		Name:         "城头土",
		StemBranches: []string{"戊寅", "己卯"},
		Element:      "土",
		ImageDesc:    "城墙之土，坚固守护，抵御外邪",
		Personality:  "有责任感，守土有责，有担当",
		EnergyStage:  "病",
		ModernExt:    "像古老的城墙，保护一方安宁",
		Judgments:    []string{"有责任感", "守土有责", "有担当"},
	},
	"砂中土": {
		Name:         "砂中土",
		StemBranches: []string{"甲辰", "乙巳"},
		Element:      "土",
		ImageDesc:    "沙砾中的土，内含金粒，蕴藏宝藏",
		Personality:  "外表平常，内有乾坤，大器晚成",
		EnergyStage:  "衰",
		ModernExt:    "像沙漠中的金砂，外表不显眼但内有宝藏",
		Judgments:    []string{"外表平常", "内有乾坤", "大器晚成"},
	},
	"路旁土": {
		Name:         "路旁土",
		StemBranches: []string{"庚午", "辛未"},
		Element:      "土",
		ImageDesc:    "道路两旁的土，承载往来，热闹之地",
		Personality:  "善于交际，人脉广泛，有社交能力",
		EnergyStage:  "死",
		ModernExt:    "像十字路口的土壤，四通八达",
		Judgments:    []string{"善于交际", "人脉广泛", "有社交能力"},
	},
	"大驿土": {
		Name:         "大驿土",
		StemBranches: []string{"丙申", "丁酉"},
		Element:      "土",
		ImageDesc:    "驿站之土，迎来送往，交流之地",
		Personality:  "善于沟通，变通灵活，人际活跃",
		EnergyStage:  "病",
		ModernExt:    "像古代的驿站，是信息和人气的集散地",
		Judgments:    []string{"善于沟通", "变通灵活", "人际活跃"},
	},
	"屋上土": {
		Name:         "屋上土",
		StemBranches: []string{"丙戌", "丁亥"},
		Element:      "土",
		ImageDesc:    "屋顶之土，遮风挡雨，守护家人",
		Personality:  "顾家有责任感，重视家庭，有奉献精神",
		EnergyStage:  "墓",
		ModernExt:    "像房屋的屋顶，庇护家人",
		Judgments:    []string{"顾家", "有责任感", "重视家庭"},
	},
}