-- 003_seed_activities.sql
-- Seed data for activity_catalog table (活动目录)
-- Defines the complete catalog of auspicious (宜) and inauspicious (忌) activities.

INSERT INTO activity_catalog (category, name, created_at, updated_at) VALUES
-- 宜 (auspicious activities) — 25 entries
('宜', '嫁娶', NOW(), NOW()),
('宜', '出行', NOW(), NOW()),
('宜', '开市', NOW(), NOW()),
('宜', '交易', NOW(), NOW()),
('宜', '立契', NOW(), NOW()),
('宜', '入宅', NOW(), NOW()),
('宜', '安床', NOW(), NOW()),
('宜', '修造', NOW(), NOW()),
('宜', '上梁', NOW(), NOW()),
('宜', '竖柱', NOW(), NOW()),
('宜', '安门', NOW(), NOW()),
('宜', '作灶', NOW(), NOW()),
('宜', '祭祀', NOW(), NOW()),
('宜', '祈福', NOW(), NOW()),
('宜', '求嗣', NOW(), NOW()),
('宜', '开光', NOW(), NOW()),
('宜', '解除', NOW(), NOW()),
('宜', '纳采', NOW(), NOW()),
('宜', '订盟', NOW(), NOW()),
('宜', '移徙', NOW(), NOW()),
('宜', '会友', NOW(), NOW()),
('宜', '入学', NOW(), NOW()),
('宜', '裁衣', NOW(), NOW()),
('宜', '纳畜', NOW(), NOW()),
('宜', '栽种', NOW(), NOW()),

-- 忌 (inauspicious activities) — 25 entries
('忌', '动土', NOW(), NOW()),
('忌', '安葬', NOW(), NOW()),
('忌', '行丧', NOW(), NOW()),
('忌', '伐木', NOW(), NOW()),
('忌', '开渠', NOW(), NOW()),
('忌', '放水', NOW(), NOW()),
('忌', '行舟', NOW(), NOW()),
('忌', '开仓', NOW(), NOW()),
('忌', '出货', NOW(), NOW()),
('忌', '置产', NOW(), NOW()),
('忌', '筑堤', NOW(), NOW()),
('忌', '补垣', NOW(), NOW()),
('忌', '塞穴', NOW(), NOW()),
('忌', '破土', NOW(), NOW()),
('忌', '啟攒', NOW(), NOW()),
('忌', '除服', NOW(), NOW()),
('忌', '成服', NOW(), NOW()),
('忌', '移柩', NOW(), NOW()),
('忌', '入殓', NOW(), NOW()),
('忌', '开生坟', NOW(), NOW()),
('忌', '合寿木', NOW(), NOW()),
('忌', '谢土', NOW(), NOW()),
('忌', '苫盖', NOW(), NOW()),
('忌', '取鱼', NOW(), NOW()),
('忌', '畋猎', NOW(), NOW());
