CREATE TABLE IF NOT EXISTS fortune_feedbacks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  chart_id BIGINT UNSIGNED NOT NULL,
  target_type VARCHAR(32) NOT NULL DEFAULT 'section',
  target_id VARCHAR(128) NOT NULL DEFAULT '',
  rating VARCHAR(32) NOT NULL,
  tags TEXT,
  comment TEXT,
  event_year INT DEFAULT 0,
  event_category VARCHAR(64) NOT NULL DEFAULT '',
  consent_research BOOLEAN NOT NULL DEFAULT FALSE,
  consent_training BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL,
  INDEX idx_fortune_feedbacks_user_id (user_id),
  INDEX idx_fortune_feedbacks_chart_id (chart_id),
  INDEX idx_fortune_feedbacks_target_type (target_type),
  INDEX idx_fortune_feedbacks_target_id (target_id),
  INDEX idx_fortune_feedbacks_rating (rating),
  INDEX idx_fortune_feedbacks_event_year (event_year),
  INDEX idx_fortune_feedbacks_event_category (event_category),
  CONSTRAINT fk_fortune_feedbacks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_fortune_feedbacks_chart FOREIGN KEY (chart_id) REFERENCES birth_charts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

